server:
  port: 8080

spring:
  application:
    name: order-service
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      indent-output: true
  
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queues:
      orders: orders
    exchanges:
      order-exchange: order-exchange
    bindings:
      - destination: orders
        exchange: order-exchange
        routing-key: orders
    listener:
      simple:
        message-converter: json
  
  rabbit:
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
          max-interval: 10000
          multiplier: 2
    connection-factory:
      addresses: localhost:5672