server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://mysql:3306/product_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
      config:
        import-check:
          enabled: false